version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3306:3307
    volumes:
      - ./../../../Back-End/webshop/db:/var/lib/mysql
  back-end:
    depends_on:
      - mysqldb
    build: ./../../../Back-End/webshop
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.datasource.initialization-mode" : "always"
        }'
    volumes:
      - ./../../../Back-End/webshop/.m2:/root/.m2
    stdin_open: true
    tty: true
  front-end:
    container_name: m210-front-end
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
volumes:
  db:


# --- 
# version: "3.7"
# 
# services: 
#   back-end: 
#     build: ./Back-End
#     depends_on: 
#       - mysqldb
#     env_file: ./.env
#     environment: # 
#       SPRING_APPLICATION_JSON: "{ \"spring.datasource.url\"  : \"jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false\", \"spring.datasource.username\" : \"$ROOT\", \"spring.datasource.password\" : \"$MYSQLDB_PASSWORD\", \"spring.jpa.properties.hibernate.dialect\" : \"org.hibernate.dialect.MySQL5InnoDBDialect\", \"spring.jpa.hibernate.ddl-auto\" : \"create\", \"spring.datasource.initialization-mode\" : \"always\" }"
#     mysqldb: ~
#     ports: 
#       - "$SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT"
#     restart: on-failure
#     stdin_open: true
#     tty: true
#     volumes: 
#       - ".m2:/root/.m2"
#   front-end-prod: 
#     build: 
#       context: "."
#       dockerfile: Dockerfile.prod
#     container_name: m210-front-end-prod
#     ports: 
#       - "1337:80"
#   mysqldb: 
#     env_file: ./.env
#     environment: # 
#       - MYSQL_USER=$MYSQLDB_USER
#       - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
#       - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#       - MYSQL_DATABASE=$MYSQLDB_DATABASE
#     image: "mysql:5.7"
#     ports: 
#       - "$MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT"
#     restart: unless-stopped
#     volumes: 
#       - "db:/var/lib/mysql"