DROP DATABASE IF EXISTS LB_Webshop;
CREATE DATABASE LB_Webshop;
USE LB_Webshop;

DROP USER LB_Webshop@'%';
CREATE USER LB_Webshop@'%' IDENTIFIED BY 'passwd';
GRANT ALL ON LB_Webshop.* to 'LB_Webshop'@'%';

CREATE TABLE BookList (
	book_id int(11) NOT NULL,
    title varchar(45) NOT NULL,
    author varchar(45) NOT NULL,
    description varchar(1000) NOT NULL,
    edition varchar(45) DEFAULT NULL,
    format varchar(45) NOT NULL,
    num_pages int(11) NOT NULL,
    rating int(11) NOT NULL,
    rating_count int(11) NOT NULL,
	review_count int(11) NOT NULL,
    genres varchar(100) NOT NULL,
    genre_list varchar(1000) NOT NULL,
    image_url varchar(1000) NOT NULL,
    Quote1 varchar(100) NOT NULL,
    Quote2 varchar(100) NOT NULL,
    Quote3 varchar(100) NOT NULL
);

INSERT INTO BookList (book_id, title, author, description, edition, format, num_pages, rating, rating_count, review_count, genres, genre_list, image_url, Quote1, Quote2, Quote3)
VALUES (1, "The Hunger Games", "Suzanne Collins", "Winning will make you famous. Losing means certain death.The nation of Panem, formed from a post-apocalyptic North America, is a country that consists of a wealthy Capitol region surrounded by 12 poorer districts. Early in its history, a rebellion led by a 13th district against the Capitol resulted in its destruction and the creation of an annual televised event known as the Hunger Games. In punishment, and as a reminder of the power and grace of the Capitol, each district must yield one boy and one girl between the ages of 12 and 18 through a lottery system to participate in the games. The 'tributes' are chosen during the annual Reaping and are forced to fight to the death, leaving only one survivor to claim victory.When 16-year-old Katniss's young sister, Prim, is selected as District 12's female representative, Katniss volunteers to take her place. She and her male counterpart Peeta, are pitted against bigger, stronger representatives, some of whom have trained for this their whole lives. , she sees it as a death sentence. But Katniss has been close to death before. For her, survival is second nature.", "", "Hardcover", 374, 4.33, 5519135, 160706, "Young Adult, Fiction, Science Fiction, Dystopia, Fantasy, Science Fiction", "Young Adult,Fiction,Science Fiction,Dystopia,Fantasy", "https://images.gr-assets.com/books/1447303603l/2767052.jpg", "“You don’t forget the face of the person who was your last hope.”", "“Remember, we're madly in love, so it's all right to kiss me anytime you feel like it.”", "”May the odds be ever in your favor!”"),
	   (2, "Harry Potter and the Order of the Phoenix", "J.K. Rowling", " is a door at the end of1 a silent corridor. And it’s haunting Harry Pottter’s dreams. Why else would he be waking in the middle of the night, screaming in terror?Harry has a lot on his mind for this, his fifth year at Hogwarts: a Defense Against the Dark Arts teacher with a personality like poisoned honey; a big surprise on the Gryffindor Quidditch team; and the looming terror of the Ordinary Wizarding Level exams. But all these things pale next to the growing threat of He-Who-Must-Not-Be-Named---a threat that neither the magical government nor the authorities at Hogwarts can stop.As the grasp of darkness tightens, Harry must discover the true depth and strength of his friends, the importance of boundless loyalty, and the shocking price of unbearable sacrifice.His fate depends on them alll.(back cover)", "US Edition", "Paperback", 870, 4.48, 2041594, 33264, "Fantasy, Young Adult, Fiction", "Fantasy, Young Adult, Fiction", "https://images.gr-assets.com/books/1255614970l/2.jpg", "“Wit beyond measure is man’s greatest treasure.”", "“Indifference and neglect often do much more damage than outright dislike.”", "“Things we lose have a way of coming back to us in the end, if not always in the way we expect.”"),
       (3, "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it, To Kill A Mockingbird became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic.Compassionate, dramatic, and deeply moving, To Kill A Mockingbird takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.", "50th Anniversary", "Paperback", 324, 4.27, 3745197, 324, 4.27, 3745197, 79450, "Classics, Fiction, Historical, Historical Fiction, Academic, School", "Classics,Fiction,Historical,Historical Fiction,Academic,School", "https://images.gr-assets.com/books/1361975680l/2657.jpg", "“Until I feared I would lose it, I never loved to read. One does not love breathing.”", "“People generally see what they look for, and hear what they listen for.”", "“The one thing that doesn't abide by majority rule is a person's conscience.”", "“It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.”"),
       (4, "Pride and Prejudice", "Jane Austen", "Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work \"her own darling child\" and its vivacious heroine, Elizabeth Bennet, \"as delightful a creature as ever appeared in print.\" The romantic clash between the opinionated Elizabeth and her proud beau, Mr. Darcy, is a splendid performance of civilized sparring. And Jane Austen's radiant wit sparkles as her characters dance a delicate quadrille of flirtation and intrigue, making this book the most superb comedy of manners of Regency England.", "Modern Library Classics, USA / CAN", "Paperback", 279, 4.25, 2453620, 54322, "Classics, Fiction, Romance", "Classics, Fiction, Romance", "https://images.gr-assets.com/books/1320399351l/1885.jpg", "“A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment.”", "“I must learn to be content with being happier than I deserve.”"),
       (5, "Twilight", "Stephenie Meyer", "About three things I was absolutely positive. First, Edward was a vampire.Second, there was a part of him—and I didn't know how dominant that part might be—that thirsted for my blood.And third, I was unconditionally and irrevocably in love with him.In the first book of the Twilight Saga, internationally bestselling author Stephenie Meyer introduces Bella Swan and Edward Cullen, a pair of star-crossed lovers whose forbidden relationship ripens against the backdrop of small-town suspicion and a mysterious coven of vampires. This is a love story with bite.", "", "Paperback", 498, 3.58, 4281268, 97991, "Young Adult, Fantasy, Romance, Paranormal, Vampires, Fiction, Fantasy, Paranormal", "Young Adult,Fantasy,Romance,Paranormal,Vampires,Fiction", "https://images.gr-assets.com/books/1361039443l/41865.jpg", "“I like the night. Without the dark, we'd never see the stars.”", "“I decided as long as I'm going to hell, I might as well do it thoroughly.”", "“When life offers you a dream so far beyond any of your expectations, it’s not reasonable to grieve when it comes to an end.”"),
       (6, "The Book Thief", "Markus Zusak", "Trying to make sense of the horrors of World War II, Death relates the story of Liesel--a young German girl whose book-stealing and story-telling talents help sustain her family and the Jewish man they are hiding, as well as their neighbors.", "First American Edition (US / CAN)", "Hardcover", 552, 4.36, 1485632, 100821, "Historical, Historical Fiction, Fiction, Young Adult", "Historical,Historical Fiction,Fiction,Young Adult", "https://images.gr-assets.com/books/1522157426l/19063.jpg", "“You don’t forget the face of the person who was your last hope.”", "“Remember, we're madly in love, so it's all right to kiss me anytime you feel like it.”", "“May the odds be ever in your favor!”"),
       (7, "The Chronicles of Narnia", "C.S. Lewis", "Journeys to the end of the world, fantastic creatures, and epic battles between good and evil—what more could any reader ask for in one book? The book that has it all is The Lion, the Witch and the Wardrobe, written in 1949 by Clive Staples Lewis. But Lewis did not stop there. Six more books followed, and together they became known as The Chronicles of Narnia.For the past fifty years, The Chronicles of Narnia have transcended the fantasy genre to become part of the canon of classic literature. Each of the seven books is a masterpiece, drawing the reader into a land where magic meets reality, and the result is a fictional world whose scope has fascinated generations.This edition presents all seven books—unabridged—in one impressive volume. The books are presented here in chronlogical order, each chapter graced with an illustration by the original artist, Pauline Baynes. Deceptively simple and direct, The Chronicles of Narnia continue to captivate fans with adventures, characters, and truths that speak to readers of all ages, even fifty years after they were first published.", "Reissue Edition", "Paperback", 767, 4.25, 437829, 9439, "Fantasy, Classics, Fiction, Young Adult, Childrens", "Fantasy,Classics,Fiction,Young Adult,Childrens", "https://images.gr-assets.com/books/1449868701l/11127.jpg", "“Wit beyond measure is man’s greatest treasure.”", "“Indifference and neglect often do much more damage than outright dislike.”", "“Things we lose have a way of coming back to us in the end, if not always in the way we expect.”"),
       (8, "Animal Farm", "George Orwell", "A farm is taken over by its overworked, mistreated animals. With flaming idealism and stirring slogans, they set out to create a paradise of progress, justice, and equality. Thus the stage is set for one of the most telling satiric fables ever penned –a razor-edged fairy tale for grown-ups that records the evolution from revolution against tyranny to a totalitarianism just as terrible.\nWhen Animal Farm was first published, Stalinist Russia was seen as its target. Today it is devastatingly clear that wherever and whenever freedom is attacked, under whatever banner, the cutting clarity and savage comedy of George Orwell’s masterpiece have a meaning and message still ferociously fresh.", "", 122, 3.9, 2235084, 42156, "Classics, Fiction, Science Fiction, Dystopia, Fantasy, Literature, Academic, School, Politics, Science Fiction, Novels, Academic, Read For School", "Classics,Fiction,Science Fiction,Dystopia,Fantasy,Literature,Academic,School,Politics,Novels,Read For School", "https://images.gr-assets.com/books/1424037542l/7613.jpg", "“Until I feared I would lose it, I never loved to read. One does not love breathing.”", "“People generally see what they look for, and hear what they listen for.”", "“The one thing that doesn't abide by majority rule is a person's conscience.”"),
       (9, "Gone with the Wind", "Margaret Mitchell", "Gone with the Wind is a novel written by Margaret Mitchell, first published in 1936. The story is set in Clayton County, Georgia, and Atlanta during the American Civil War and Reconstruction era. It depicts the struggles of young Scarlett O'Hara, the daughter of a well-to-do plantation owner, who must use every means at her disposal to claw her way out of the poverty she finds herself in after Sherman's March to the Sea. A historical novel, the story is a Bildungsroman or coming-of-age story, with the title taken from a poem written by Ernest Dowson.", "", "Paperback", 1037, 4.29, 969181, 17452, "Classics, Historical, Historical Fiction, Fiction, Romance, Historical", "Classics,Historical,Historical Fiction,Fiction,Romance", "https://images.gr-assets.com/books/1328025229l/18405.jpg", "“A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment.”", "“It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.”","“I must learn to be content with being happier than I deserve.”"),
       (10, "J.R.R. Tolkien 4-Book Boxed Set: The Hobbit and The Lord of the Rings", "J.R.R. Tolkien", "This four-volume, boxed set contains J.R.R. Tolkien's epic masterworks The Hobbit and the three volumes of The Lord of the Rings (The Fellowship of the Ring, The Two Towers, and The Return of the King).", "Hobbit Movie Tie-in Boxed set", "Mass Market Paperback", 1728, 4.59, 99793, 1652, "Fantasy, Fiction, Classics", "Fantasy,Fiction,Classics", "https://images.gr-assets.com/books/1346072396l/30.jpg", "“I like the night. Without the dark, we'd never see the stars.”", "“I decided as long as I'm going to hell, I might as well do it thoroughly.”", "“When life offers you a dream so far beyond any of your expectations, it’s not reasonable to grieve when it comes to an end.”"),
       (11, "The Fault in Our Stars", "John Green", "Despite the tumor-shrinking medical miracle that has bought her a few years, Hazel has never been anything but terminal, her final chapter inscribed upon diagnosis. But when a gorgeous plot twist named Augustus Waters suddenly appears at Cancer Kid Support Group, Hazel's story is about to be completely rewritten. Insightful, bold, irreverent, and raw, The Fault in Our Stars is award-winning author John Green's most ambitious and heartbreaking work yet, brilliantly exploring the funny, thrilling, and tragic business of being alive and in love.", "", "Hardcover", 313, 4.24, 2881648, "Young Adult, Fiction, Romance, Contemporary", "Young Adult,Fiction,Romance,Contemporary","https://images.gr-assets.com/books/1360206420l/11870085.jpg", "“You don’t forget the face of the person who was your last hope.”", "“Remember, we're madly in love, so it's all right to kiss me anytime you feel like it.”", "“May the odds be ever in your favor!”"),
       (12, "The Hitchhiker's Guide to the Galaxy", "Douglas Adams", "Seconds before the Earth is demolished to make way for a galactic freeway, Arthur Dent is plucked off the planet by his friend Ford Prefect, a researcher for the revised edition of The Hitchhiker's Guide to the Galaxy who, for the last fifteen years, has been posing as an out-of-work actor.Together this dynamic pair begin a journey through space aided by quotes from The Hitchhiker's Guide (\"A towel is about the most massively useful thing an interstellar hitchhiker can have\") and a galaxy-full of fellow travelers: Zaphod Beeblebrox—the two-headed, three-armed ex-hippie and totally out-to-lunch president of the galaxy; Trillian, Zaphod's girlfriend (formally Tricia McMillan), whom Arthur tried to pick up at a cocktail party once upon a time zone; Marvin, a paranoid, brilliant, and chronically depressed robot; Veet Voojagig, a former graduate student who is obsessed with the disappearance of all the ballpoint pens he bought over the years.", "", "Paperback", 193, 4.21, 1155911, 23919, "Science Fiction, Fiction, Humor, Fantasy, Classics", "Science Fiction,Fiction,Humor,Fantasy,Classics", "https://images.gr-assets.com/books/1388282444l/386162.jpg", "“Wit beyond measure is man’s greatest treasure.”", "“Indifference and neglect often do much more damage than outright dislike.”", "“Things we lose have a way of coming back to us in the end, if not always in the way we expect.”"),
       (13,)
       (14,)
       (15,)
       (16,)
       (17,)
       (18,)
       (19,)
       (20,)
       (21,)
       (22,)
       (23,)
       (24,)
       (25,)
       (26,)
       (27,)
       (28,)
       (29,)
       (30,)
       (31,)
       (32,)
       (33,)
       (34,)
       (35,)
       (36,)
       (37,)
       (38,)
       (39,)
       (40,)
       (41,)
       (42,)
       (43,)
       (44,)
       (45,)
       (46,)
       (47,)
       (48,)
       (49,)
       (50,)